### ISSUE TITLE
Can't split long interpolated strings

### ISSUE THREAD

**Issue by nilvon9wo** [Drizin/InterpolatedLogging#4]
I have the following code:

```
_logger.InterpolatedError($"Could not delete record from {clientFieldName:Client}/{userFieldName:User}, submitted at {submitTime:SubmitTime}: {saveResposne.Errors:@Errors}");
```

This is a bit wider than feels comfortable, so I want to split it like:

```
                _logger.InterpolatedError($"Could not delete record from {clientFieldName:Client}/{userFieldName:User}, " +
                    $"submitted at {submitTime:SubmitTime}: {saveResposne.Errors:@Errors}");

```

Unfortunately, Visual Studio 2022 complains:
```
Error	CS1503	Argument 2: cannot convert from 'string' to 'System.FormattableString'	
```

**Comment by Drizin** [comment]
The "+" sign applied on two FormattableStrings (interpolated strings) will cause them both (as well as the end result) to be converted to string. The library doesn't take strings, it needs to be FormattableStrings.
Use $@ to do multi-line interpolated strings:
```
_logger.InterpolatedError($@"Could not delete record from {clientFieldName:Client}/{userFieldName:User}, 
                    submitted at {submitTime:SubmitTime}: {saveResposne.Errors:@Errors}");
```

**Comment by nilvon9wo** [comment]
Good to know!  :-)

(I guess an alternative, more ambitious fix would be to override the "+" operator so the output could be another formatted string?  But I don't know if that is actually possible and I guess it's not worth it if we can use the "$@" ....)

**Comment by Drizin** [comment]
Doesn't sound like a bad idea. 
Looks like using a custom class (inheriting from FormattableString) and using [operator overloading](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading) on this class, plus some implicit conversions, it should be possible to do things like:

```
logger.InterpolatedInfo(new JoinableString()
   + $"User {name:UserName}"
   + $"created Order {orderId:OrderId}"
);
```

I'm working on this idea. Thanks for the suggestion.

**Comment by Drizin** [comment]
@nilvon9wo please take a look at my last commit. Let me know your thoughts.
