### ISSUE TITLE
Whitespace breaks interpolation

### ISSUE THREAD

**Issue by nilvon9wo** [Drizin/InterpolatedLogging#5]
I accidently included some whitespace like this:

```
_logger.InterpolatedError(ex, $"Job failed {key: Job}");
```

I didn't think whitespace would matter and thought this a little more readable than:

```
_logger.InterpolatedError(ex, $"Job failed {key:Job}");
```

However, the result was the value of `key` was not rendered. (However, "Job" appeared where expected.)

**Comment by Drizin** [comment]
I think you can trim leading spaces (`TrimStart(' ')`) after argFormat is extracted ([here](https://github.com/Drizin/InterpolatedLogging/blob/main/src/InterpolatedLogging/StructuredLogMessage.cs#L97)). Would you like to test and submit a PR?

**Comment by nilvon9wo** [comment]
@Drizin , sorry, but as much as I want to support your efforts, I don't have a lot of time to do development and testing right now.... My fulltime job already has my attention divided between 3 projects, not including several on the backburner which don't always stay there.

If I find some time before you fix it though, I'll let you know.  ;-)
