### ISSUE TITLE
Null value results in an exception

### ISSUE THREAD

**Issue by nilvon9wo** [Drizin/InterpolatedLogging#6]
I have the following code:

```
                SyncJobState jobState = await _dbContext.SyncJobs.Find(x => x.Job == key).SingleOrDefaultAsync(cancellationToken);
                DateTime? prevJobTime = jobState?.LastSynchronization;
                DateTime jobStartTime = DateTime.UtcNow;
                _logger.InterpolatedInformation($"Executing job {key:Job}; previous run: {prevJobTime:LastSync}");
```

Of course, the sometimes, there is no value for `prevJobTime`, in which case the value is null.

which results in:

>System.NullReferenceException: Object reference not set to an instance of an object.
>   at System.Object.GetType()
>   at InterpolatedLogging.StructuredLogMessage.ParseInner(String format, Object[] arguments)
>   at InterpolatedLogging.StructuredLogMessage.Parse()
>   at InterpolatedLogging.StructuredLogMessage.get_MessageTemplate()
>   at Microsoft.Extensions.Logging.InterpolatedLoggingExtensions.InterpolatedInformation(ILogger logger, FormattableString message)

It's probably not a great practice to require null checks before logging...

**Comment by Drizin** [comment]
@nilvon9wo whoa, that was really an ugly bug. Thanks for reporting.
It's fixed in latest nugets. Can you please try it and confirm? 
Thanks!
