### ISSUE TITLE
[Suggestion] Support for EventId on Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by Whivel** [Drizin/InterpolatedLogging#8]
Adding the support for the method overloads that use EventId could be useful

**Comment by Drizin** [comment]
Yeah, looks like an important feature.
Would you like to submit a PR for that?

**Comment by Drizin** [comment]
Done, published as InterpolatedLogging.Microsoft.Extensions.Logging.5.1.0
Thanks for the suggestion!
